### ISSUE TITLE
Init and Shutdown Checklist

### ISSUE THREAD

**Issue by jskimko** [tablackwell/chromablade#11]
### Startup
* Message box and exit on failure
1. Load text
2. Load essential data
3. Init video system
4. Check for multiple instances
* [ ] Init RNGs
* [ ] Create window
* [ ] Init sound system
* [ ] Load user options
* [ ] Init subsystems (AI, physics, etc)
* [ ] ? Check resources (memory)
* [ ] ? Load programmer options
* [ ] ? Init memory cache

### Shutdown
* [ ]  Player quits
  * [ ] Prompt save if no recent save
  * [ ] Check Alt-F4 (account for spam)
* [ ] OS kills game
  * [ ] Make backup save-game

##### References
* 4
