### ISSUE TITLE
Resource Cache Checklist

### ISSUE THREAD

**Issue by jskimko** [tablackwell/chromablade#14]
* [ ] Preload maps when switching
* [ ] Load Player sprite sheet
* [ ] Load Mob sprite sheet
* [ ] Load Greyscale sprite sheet

### Guidelines
* Predefined size
* Load compressed archive in memory
* Decompress files on demand
* Remove archives when cache is full

### Notes
* Images, Video, Sound, Text, Level data, Character data, ...
* Pack files in chunks in big files and compress (zlib)
