### ISSUE TITLE
Map Design Checklist for Cycle 2

### ISSUE THREAD

**Issue by tablackwell** [tablackwell/chromablade#16]
**Map File for the Cycle 2 Demo**
- [x] Design custom tilesets by taking tiles from LoZ tilesets
- [x] Village (The Hub)
- [x] Red Dungeon (Tutorial dungeon)
- [x] Begin drafting other dungeons
- [x] Begin drafting greyscale dungeon
