### ISSUE TITLE
Game Architecture Checklist

### ISSUE THREAD

**Issue by jskimko** [tablackwell/chromablade#7]
* [ ] Game Application Layer
  * [ ] Devices
    * [ ] Input #13 
    * [ ] Files #14 
    * [ ] RAM
    * [ ] Time
  * [ ] OS
    * [ ] Language
    * [ ] Dynamic Libraries
    * [ ] Threads
    * [ ] Network
  * [ ] Game State
    * [ ] Core Lib
    * [ ] Main Loop #10 
    * [ ] Init and shutdown #11 
* [ ] Game Logic
  * [ ] Game state & Data structures #9 
  * [ ] Physics
  * [ ] Events #12 
  * [ ] Process Manager
  * [ ] Command Interpreter
* [ ] Game View
  * [ ] Player View
    * [ ] Display #8 
    * [ ] Audio
    * [ ] Input Interpreter
    * [ ] Process Manager
    * [ ] Options
  * [ ] AI View
    * [ ] Stimulus Interpreter
    * [ ] Decision System
    * [ ] Process Manager
    * [ ] Options
  * [ ] ~Network View~
